---

variables:
  AWS_DTR_URL: "955466075186.dkr.ecr.cn-northwest-1.amazonaws.com.cn"
  PRIVATE_DTR_URL: ${AWS_DTR_URL}
  TEAM: "ops"
  PROJECT_TYPE: "s"
  PROJECT_NAME: "piam"
  HC_PORT: "80"
  HC_HTTP_REQUEST_PATH: "/health"
  HC_PER_SEC: "60"
  PRIVILEGE: "yes"

# TODO: add test stage for automatic system test and etc.
stages:
  - init
  - build
  - deploy

#################################### Init ####################################
init:
  stage: init
  tags:
    - aws
    - docker
  when: manual
  script:
    - ops_deploy init

init_manager:
  stage: init
  when: manual
  tags:
    - aws
    - docker
  variables:
    PROJECT_NAME: "piam-manager"
    GIT_STRATEGY: none
#  only:
#    - master
  script:
    - ops_deploy init

#################################### Build ####################################
build_manager:
  stage: build
  tags:
    - aws
    - docker
  #  when: manual
  script:
    - export http_proxy="http://10.40.40.12:8118" &&export https_proxy="http://10.40.40.12:8118"
    - export MANAGER="${PRIVATE_DTR_URL}/${TEAM}/${PROJECT_TYPE}-${TEAM}-piam-manager:${CI_COMMIT_REF_NAME}-${CI_PIPELINE_ID}"
    - docker build --build-arg package=piam-manager -t ${MANAGER} --target runtime .
    - docker images | grep "piam-manager"
    - docker push ${MANAGER}
    - echo ${MANAGER}

############################### Deploy manager ###############################
deploy_manager_cn_aws_qa:
  stage: deploy
  tags:
    - aws
    - docker
#  when: manual
  variables:
    ENV: qa
    PROJECT_NAME: "piam-manager"
    REGION: cn-northwest-1
    K8STYPE: eks
    GIT_STRATEGY: none
  before_script:
    - echo $image
  script:
    - ops_deploy deploy
