---

variables:
  #以下两个是容器仓库地址，写死
  AWS_DTR_URL: "955466075186.dkr.ecr.cn-northwest-1.amazonaws.com.cn"
  PRIVATE_DTR_URL: ${AWS_DTR_URL}
  #组名, 示例是rd，根据实际修改
  TEAM: "ops"
  #服务类型，内部服务为s外服服务为w前端为f"
  PROJECT_TYPE: "s"
  #服务名 
  PROJECT_NAME: "piam"
  #健康检查端口
  HC_PORT: "8080"
  #健康检查路径
  HC_HTTP_REQUEST_PATH: "/health"
  #服务发布与更新后的健康检查延迟检测时间
  HC_PER_SEC: "60"
  #新增发到生产跳过审批
  PRIVILEGE: "yes"

stages:
  - init
  - build
  - deploy

#################################### Init ####################################
init:
  stage: init
  tags:
    - aws
    - docker
  when: manual
  script:
    - ops_deploy init

init_manager:
  stage: init
  when: manual
  tags:
    - aws
    - docker
  variables:
    PROJECT_NAME: "piam-manager"
    GIT_STRATEGY: none
#  only:
#    - master
  script:
    - ops_deploy init

init_s3proxy:
  stage: init
  when: manual
  tags:
    - aws
    - docker
  variables:
    PROJECT_NAME: "piam-s3-proxy"
    GIT_STRATEGY: none
#  only:
#    - master
  script:
    - ops_deploy init

#################################### Build ####################################
build_manager:
  stage: build
  tags:
    - aws
    - docker
  #  when: manual
  script:
    - export MANAGER="${PRIVATE_DTR_URL}/${TEAM}/${PROJECT_TYPE}-${TEAM}-piam-manager:${CI_COMMIT_REF_NAME}-${CI_PIPELINE_ID}"
    - docker build --build-arg package=piam-manager -t ${MANAGER} --target runtime .
    - docker push ${MANAGER}
    - echo ${MANAGER}

build_s3_proxy:
  stage: build
  tags:
    - aws
    - docker
#  when: manual
  script:
    - export S3PROXY="${PRIVATE_DTR_URL}/${TEAM}/${PROJECT_TYPE}-${TEAM}-piam-s3-proxy:${CI_COMMIT_REF_NAME}-${CI_PIPELINE_ID}"
    - docker build --build-arg package=piam-s3-proxy -t ${S3PROXY} --target runtime .
    - docker push ${S3PROXY}
    - echo ${S3PROXY}

############################### Deploy manager ###############################
deploy_manager_cn_aws_qa:
  stage: deploy
  tags:
    - aws
    - docker
#  when: manual
  variables:
    ENV: qa
    PROJECT_NAME: "piam-manager"
    REGION: cn-northwest-1
    K8STYPE: eks
    GIT_STRATEGY: none
  before_script:
    - echo $image
  script:
    - ops_deploy deploy

############################### Deploy s3 proxy ###############################
deploy_s3_proxy_us_aws_prod:
  stage: deploy
  tags:
    - aws
    - docker
#  when: manual
  variables:
    ENV: prod
    PROJECT_NAME: "piam-s3-proxy"
    REGION: us-east-1
    K8STYPE: eks
    GIT_STRATEGY: none
  before_script:
    - echo $image
  script:
    - ops_deploy deploy

deploy_s3_proxy_cn_aws_qa:
  stage: deploy
  tags:
    - aws
    - docker
  #  when: manual
  variables:
    ENV: qa
    PROJECT_NAME: "piam-s3-proxy"
    REGION: cn-northwest-1
    K8STYPE: eks
    GIT_STRATEGY: none
  before_script:
    - echo $image
  script:
    - ops_deploy deploy


deploy_s3_proxy_cn_tencent_qa:
  stage: deploy
  tags:
    - aws
    - docker
  #  when: manual
  variables:
    ENV: qa
    PROJECT_NAME: "piam-s3-proxy"
    REGION: ap-shanghai
    K8STYPE: eks
    GIT_STRATEGY: none
  before_script:
    - echo $image
  script:
    - ops_deploy deploy

deploy_s3_proxy_us_tencent_data-prod:
  stage: deploy
  tags:
    - aws
    - docker
  #  when: manual
  variables:
    ENV: prod
    PROJECT_NAME: "piam-s3-proxy"
    REGION: na-ashburn
    K8STYPE: eks
    GIT_STRATEGY: none
  before_script:
    - echo $image
  script:
    - ops_deploy deploy
