[profile.release-with-debug]
inherits = "release"
debug = true

[workspace]

members = [
    "crates/piam-manager",
    "crates/piam-object-storage",
    "crates/piam-core",
    "crates/piam-proxy",
]
