rust_dev:
  image: '955466075186.dkr.ecr.cn-northwest-1.amazonaws.com.cn/ops-basic/base:rust-dev-git-ssh'
  restart: always
  hostname: 'rust_dev'
  environment:
    TZ: Asia/Shanghai
    REDIS_ADDRESS: redis://192.168.3.233:6379/1
    PIAM_MANAGER_ADDRESS: http://192.168.3.233:8080
  ports:
    - '80:80'
    - '8080:8080'
  volumes:
    - '/data/gitlab/piam:/data/gitlab/piam'
    - '/data/gitlab/workspace/.bashrc:/root/.bashrc'
    - '/root/.ssh:/root/.ssh'
    - '/usr/local/cargo:/usr/local/cargo'
  entrypoint: tail -f /dev/null