[package]
name = "piam-s3-proxy"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

#[features]
#s3 = ["aws-sdk-s3"]
#sqs = []

[dependencies]
axum = "0.6.0-rc.2"
axum-core = "0.3.0-rc.1"
hyper = { version = "0.14", features = ["full"] }
tokio = { version = "1", features = ["full"] }
log = "0.4.17"
aws-config = "0.48.0"
aws-smithy-client = "0.48.0"
aws-sdk-s3 = { version = "0.18.0" }
aws-types = "0.48.0"
time = "0.3.14"
uuid = { version = "1.1.2", features = ["v4", "fast-rng", "macro-diagnostics"] }
futures = "0.3.24"
piam-core = { path = "../piam-core", features = ["s3-policy"] }
piam-tracing = { path = "../piam-tracing" }
http = "0.2.8"
anyhow = "1.0"
url = "2.2.2"
uriparse = "0.6.4"
serde_urlencoded = "0.7.1"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
arc-swap = "1.5.1"
once_cell = "1.15.0"
