[source.crates-io]
replace-with = 'tuna'

[source.tuna]
registry = "https://mirrors.tuna.tsinghua.edu.cn/git/crates.io-index.git"

#[source.crates-io]
#replace-with = 'ustc'
#
#[source.ustc]
#registry = "git://mirrors.ustc.edu.cn/crates.io-index"

#[target.x86_64-unknown-linux-musl]
#linker = "x86_64-linux-musl-gcc"

[target.x86_64-pc-windows-gnu]
linker = "x86_64-w64-mingw32-gcc"
