[package]
name = "piam-manager"
version = "0.1.0"
edition = "2021"

[dependencies]
piam-tracing = { path = "../piam-tracing" }
axum = { version = "0.6.1", features = ["tokio"] }
hyper = { version = "0.14", features = ["full"] }
tokio = { version = "1", features = ["full"] }
log = "0.4.17"
redis = "0.21.6"
arc-swap = "1.5.1"
once_cell = "1.15.0"
serde = { version = "1.0", features = ["derive"] }

[dev-dependencies]
piam-proxy-core = { path = "../piam-proxy-core", features = ["object-storage-policy", "aws-xml-response"] }
uuid = { version = "1.1.2", features = ["v4", "fast-rng", "macro-diagnostics"] }
serde_yaml = "0.9"
