[package]
name = "piam-manager"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
piam-tracing = { path = "../piam-tracing" }
axum = "0.5.16"
hyper = { version = "0.14", features = ["full"] }
tokio = { version = "1", features = ["full"] }
log = "0.4.17"
redis = "0.21.6"
arc-swap = "1.5.1"
once_cell = "1.15.0"
